from . import product_template
from . import product_category
from . import product_supplierinfo
from . import product_pricelist
from . import product_subscription
from . import product_identifier
from . import product_attribute
from . import product_taxes
from . import res_partner
from . import subscription_cache
from . import product_availability